language: python

python:
  - "3.11"

services:
  - postgresql

before_script:
  - psql -c 'create database customer_club;' -U postgres

install:
  - pip install -r requirements.txt
  - python manage.py migrate

script:
  - pytest
