# Generated by Django 5.0.6 on 2024-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_english_name", models.CharField(max_length=100)),
                ("group_persian_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "customer_groups",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=11)),
                ("points", models.PositiveIntegerField(default=0)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("wedding_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("member_of", models.ManyToManyField(to="accounts.group")),
            ],
            options={
                "db_table": "customer",
            },
        ),
    ]
