# Generated by Django 5.0.6 on 2024-06-04 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.PositiveIntegerField()),
                ("status", models.IntegerField()),
                ("status_text", models.CharField(max_length=500)),
                ("message", models.TextField()),
                ("cost", models.IntegerField()),
                ("receptor", models.CharField(max_length=11)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("BIRTHDAY", "Sent a message for birthday."),
                            ("WEDDING_DATE", "Sent a message for wedding date."),
                            (
                                "GROUP_SINGLE_MESSAGE",
                                "Sent a single message for a group/groups.",
                            ),
                            (
                                "GROUP_ARRAY_MESSAGE",
                                "Sent an special message for each customer in group/groups (Array message).",
                            ),
                            ("SEND_A_MESSAGE", "Sent a message to a customer."),
                            (
                                "REMAIN_CREDIT_MESSAGE",
                                "Sent a warning message to a admin to recharge credit.",
                            ),
                            (
                                "WARNING_MESSAGE",
                                "Sent a warning message to a admin to for a problem.",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "message_log",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE_CUSTOMER", "created a new customer"),
                            ("CREATE_USER", "created a new user"),
                            ("CREATE_GROUP", "created a new group for customers"),
                            (
                                "CREATE_MESSAGE",
                                "created a new message for birthday or wedding day",
                            ),
                            ("DELETE_CUSTOMER", "deleted a customer"),
                            ("DELETE_USER", "deleted a user"),
                            ("DELETE_GROUP", "deleted a group"),
                            ("DELETE_MESSAGE", "deleted one of the built in messages"),
                            ("UPDATE_CUSTOMER", "updated one of the customers"),
                            ("UPDATE_USER", "updated one of the users"),
                            ("UPDATE_GROUP", "updated one of the groups"),
                            ("UPDATE_MESSAGE", "updated one of the messages"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "actions",
            },
        ),
        migrations.CreateModel(
            name="BuiltInMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=900)),
                ("is_birthday", models.BooleanField(default=False)),
                ("is_wedding_date", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "messages",
                "indexes": [
                    models.Index(
                        fields=["deleted_at"], name="messages_deleted_555c2c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("gruops", models.ManyToManyField(to="customers.group")),
            ],
            options={
                "db_table": "chart_data",
            },
        ),
    ]
