# Generated by Django 5.0.6 on 2024-05-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_customer_deleted_3c8347_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuiltInMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=900)),
                ("is_birthday", models.BooleanField(default=False)),
                ("is_wedding_date", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["deleted_at"], name="messaging_b_deleted_49f034_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SendLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("gruops", models.ManyToManyField(to="customers.group")),
            ],
        ),
    ]
