# Generated by Django 5.0.6 on 2024-05-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="builtinmessage",
            new_name="messages_deleted_555c2c_idx",
            old_name="messaging_b_deleted_49f034_idx",
        ),
        migrations.AlterModelTable(
            name="builtinmessage",
            table="messages",
        ),
    ]
