# Generated by Django 5.0.6 on 2024-05-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "messaging",
            "0002_rename_messaging_b_deleted_49f034_idx_messages_deleted_555c2c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sendlogs",
            table="message_logs",
        ),
    ]
