# Generated by Django 5.0.6 on 2024-05-26 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_customer_deleted_3c8347_idx_and_more"),
        ("messaging", "0003_alter_sendlogs_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SendLogs",
            new_name="SendLog",
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE_CUSTOMER", "created a new customer"),
                            ("CREATE_USER", "created a new user"),
                            ("CREATE_GROUP", "created a new group for customers"),
                            (
                                "CREATE_MESSAGE",
                                "created a new message for birthday or wedding day",
                            ),
                            ("DELETE_CUSTOMER", "deleted a customer"),
                            ("DELETE_USER", "deleted a user"),
                            ("DELETE_GROUP", "deleted a group"),
                            ("DELETE_MESSAGE", "deleted one of the built in messages"),
                            ("UPDATE_CUSTOMER", "updated one of the customers"),
                            ("UPDATE_USER", "updated one of the users"),
                            ("UPDATE_GROUP", "updated one of the groups"),
                            ("UPDATE_MESSAGE", "updated one of the messages"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "actions",
            },
        ),
    ]
