# Generated by Django 5.0.6 on 2024-06-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_rename_sendlogs_sendlog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.PositiveIntegerField()),
                ("status", models.IntegerField()),
                ("status_text", models.CharField()),
                ("message", models.TextField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("BIRTHDAY", "Sent a message for birthday."),
                            ("WEDDING_DATE", "Sent a message for wedding date."),
                            (
                                "GROUP_SINGLE_MESSAGE",
                                "Sent a single message for a group/groups.",
                            ),
                            (
                                "GROUP_ARRAY_MESSAGE",
                                "Sent an special message for each customer in group/groups (Array message).",
                            ),
                            ("SEND_A_MESSAGE", "Sent a message to a customer."),
                            (
                                "REMAIN_CREDIT_MESSAGE",
                                "Sent a warning message to a admin to recharge credit.",
                            ),
                            (
                                "WARNING_MESSAGE",
                                "Sent a warning message to a admin to for a problem.",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
