# Generated by Django 5.0.6 on 2024-06-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_messagelog"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="messagelog",
            table="message_log",
        ),
    ]
