# Generated by Django 5.0.6 on 2024-06-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_alter_messagelog_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sendlog",
            table="chart_data",
        ),
    ]
