# Generated by Django 5.0.6 on 2024-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_alter_sendlog_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagelog",
            name="status_text",
            field=models.CharField(max_length=500),
        ),
    ]
