# Generated by Django 5.0.6 on 2024-06-03 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_english_name", models.CharField(max_length=100)),
                ("group_persian_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer_groups",
                "indexes": [
                    models.Index(
                        fields=["deleted_at"], name="customer_gr_deleted_8b3d6b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=255, null=True)),
                ("lastname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid Phone Number",
                                regex="^(?:\\+98|0)9\\d{9}$",
                            ),
                            django.core.validators.MinLengthValidator(
                                11, "Phone number is too short, it must be 11 chars."
                            ),
                            django.core.validators.MaxLengthValidator(
                                11, "Phone number is too long, it must be 11 chars."
                            ),
                        ],
                    ),
                ),
                ("points", models.PositiveIntegerField(blank=True, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("wedding_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("member_of", models.ManyToManyField(to="customers.group")),
            ],
            options={
                "db_table": "customer",
                "indexes": [
                    models.Index(
                        fields=["deleted_at"], name="customer_deleted_3c8347_idx"
                    )
                ],
            },
        ),
    ]
