# Generated by Django 5.0.6 on 2024-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_customer_deleted_3c8347_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="firstname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lastname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
